### ISSUE TITLE
Could you please tell me the nodeJS version number you are using

### ISSUE THREAD

**Issue by liyinchigithub** [kevinGodell/ffmpeg-streamer#11]
hello
Could you please tell me the nodeJS version number you are using

**Comment by kevinGodell** [comment]
Can I presume that you mean the nodejs version bundled with the releases using pkg? If yes, it was packaged feb 2, 2019, so that means it could be <= 11.9.0. I really can't remember. I haven't touched this code in years. In retrospect, I probably should have documented the nodejs version.

**Comment by liyinchigithub** [comment]
@kevinGodell  thank you so much
