### ISSUE TITLE
Multiply process, different inputs and dynamic streams identifier 

### ISSUE THREAD

**Issue by MomoDeLuxe** [kevinGodell/ffmpeg-streamer#3]
Is it possible to achieve that with current dist?!

**Comment by kevinGodell** [comment]
I am not sure what question you are asking. It was designed for a single input to create 6 output types to compare them. Can you give more detail so I can give you a better response?
[live example](http://kevin.shinobi.video:3000/)

**Comment by MomoDeLuxe** [comment]
I've contacted you to your mail, please check!!
