### ISSUE TITLE
default files and settings -- nothing happens (black screen)

### ISSUE THREAD

**Issue by saket424** [kevinGodell/ffmpeg-streamer#4]
I tried to use the default and I don't see anything happening other than 503. Am I doing something wrong?

ffmpeg-streamer ver: 0.0.12
ffmpeg ver: 2.8.15-0ubuntu0.16.04.1

-loglevel info -progress pipe:3 -hwaccel auto -analyzeduration 10000000 -probesize 1048576 -re -f hls -i http://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/hls/TearsOfSteel.m3u8 -c:a aac -c:v copy -f mp4 -movflags +dash+negative_cts_offsets pipe:1 -c mjpeg -q 10 -r 7 -vf scale=trunc(iw*0.75/2)*2:-2 -f image2pipe pipe:4

anand@ubulap2:~/ffmpeg-streamer$ npm run dev

> ffmpeg-streamer@0.0.12 dev /home/anand/ffmpeg-streamer
> node --trace-warnings app 3000 development

Listening on port 3000.
GET / 200 14.306 ms - 42836
GET /mdi/material-icons.css 304 5.415 ms - -
GET /mdl/material.deep_orange-blue.min.css 304 2.626 ms - -
GET /mdl/material.min.js 304 2.352 ms - -
GET /images/forkme_right_orange_ff7600.png 304 7.879 ms - -
GET /javascripts/index.js 304 0.626 ms - -
GET /mdi/MaterialIcons-Regular.woff2 304 0.916 ms - -
POST / 200 25.244 ms - 5681
GET /mdi/material-icons.css 304 1.594 ms - -
GET /mdl/material.deep_orange-blue.min.css 304 0.441 ms - -
GET /assets/hls.min.js 304 3.784 ms - -
GET /mdl/material.min.js 304 1.307 ms - -
GET /javascripts/player.js 304 1.769 ms - -
GET /javascripts/video.js 304 1.799 ms - -
GET /hls/test.m3u8 503 1.082 ms - 14
GET /mdi/MaterialIcons-Regular.woff2 304 1.696 ms - -
GET /mp4/test.mp4?t=1:28:23_PM 503 0.460 ms - 13
GET /hls/test.m3u8 503 0.395 ms - 14
GET /mp4/test.mp4?t=1:28:24_PM 503 0.266 ms - 13
GET /mp4/test.mp4?t=1:28:24_PM 503 0.274 ms - 13
GET /hls/test.m3u8 503 0.289 ms - 14
GET /mp4/test.mp4?t=1:28:25_PM 503 0.491 ms - 13
GET /mp4/test.mp4?t=1:28:25_PM 503 0.296 ms - 13
GET /mp4/test.mp4?t=1:28:26_PM 503 0.679 ms - 13
GET /mp4/test.mp4?t=1:28:26_PM 503 0.382 ms - 13
GET /hls/test.m3u8 503 0.345 ms - 14
GET /mp4/test.mp4?t=1:28:27_PM 503 0.627 ms - 13
GET /mp4/test.mp4?t=1:28:28_PM 503 0.267 ms - 13
GET /mp4/test.mp4?t=1:28:28_PM 503 0.237 ms - 13
GET /mp4/test.mp4?t=1:28:29_PM 503 0.240 ms - 13
GET /mp4/test.mp4?t=1:28:29_PM 503 0.234 ms - 13
GET /mp4/test.mp4?t=1:28:30_PM 503 0.541 ms - 13
GET /mp4/test.mp4?t=1:28:30_PM 503 0.240 ms - 13
GET /hls/test.m3u8 503 0.291 ms - 14

**Comment by saket424** [comment]
when I updated ffmpeg to 3.4.2 (https://www.johnvansickle.com/ffmpeg/old-releases/ffmpeg-3.4.2-64bit-static.tar.xz) , things started working with default settings

so apparently ffmpeg 2.8.15 is not sufficient

**Comment by kevinGodell** [comment]
Thanks for following up so quickly. You could have visited your server address and put "/install" added on to url to get option to install ffmpeg, too.

**Comment by pattarmanjunath50** [comment]
I have ffmpeg 3.4.4 installed. I want to view the IP camera streams which is throwing the same error when I used rtsp url of the camera. Have I missed something?

**Comment by kevinGodell** [comment]
hi @pattarmanjunath50 . Can you give me a little more details?
- how did you start the process
- what os are you running it on
- did the test stream work
- is your ip cam publicly accessible so that i can try to view it
- did you try the test app @ http://kevin.shinobi.video:3000/

**Comment by pattarmanjunath50** [comment]
Hi, 
thank you for replying.
The OS i am using is Ubuntu 16.04 which is connected to a private network which consists of IP cameras connected to that network. And I started the process by providing the rtsp url of the IP camera in the UI on localhost:3000

When I proceeded after giving the rtsp url, The console had error as mentioned above by  @saket424

Since the IP cam is not publicly accessible, it didn't work in the test app.

**Comment by kevinGodell** [comment]
I just tried ffmpeg-streamer on my ubuntu, mac, and windows machines and it still works for me, so there must be some setting that is making ffmpeg crash. 

Did you ever try to run it with the default parameters and video stream that is pre-populated, assuming that your ubuntu box has internet access?
