### ISSUE TITLE
How can I use this program to process multiple requests

### ISSUE THREAD

**Issue by wangmaoguo** [kevinGodell/ffmpeg-streamer#6]
Hello , this is a great project , and now i am trying to use it .but now i have a different issue.
How can I use this program to process multiple requests?

for example:
Now I have more than one rtsp request, how can i handle these requests?

**Comment by kevinGodell** [comment]
hi @wangmaoguo ffmpeg-streamer was designed to test a single video input. If you are in need of processing multiple rtsp camera inputs, you should look at my other [test project](https://github.com/kevinGodell/mse-live-player) that I use to watch my 14 rtsp ip cams. It is very simplistic, but it may give you a start to what you are trying to accomplish.
