### ISSUE TITLE
Why 10 instances limit

### ISSUE THREAD

**Issue by collaorodrigo7** [kevinGodell/ffmpeg-streamer#8]
First of all, what a great project man, thanks for sharing it. I have been trying to do this my self for a while but yours is way more advanced already.

I was wondering why in the docs you mention the app can be run, up to a total of 10 times?
Why would you be able to run it more than 10 times, if your hardware can handle it?
(I have not tested to run it more than 10 times yet, but I was just curious about it)

**Comment by kevinGodell** [comment]
Wow, my old code is pretty ugly. Really needs to be rebuilt.

The docs wasn't very clear. If you tried to use it on a port that was in use, it would keep incrementing the port until it found one available. I figured 10 was a safe number of attempts before giving up.

If you specify a unique port for each instance, you can have more than 10 running.

**Comment by collaorodrigo7** [comment]
awesome thanks for your help!
