### ISSUE TITLE
Problem with HLS

### ISSUE THREAD

**Issue by collaorodrigo7** [kevinGodell/ffmpeg-streamer#9]
I have been spending a couple days looking at the project and even more time looking at:
https://github.com/kevinGodell/mse-live-player

And I noticed something.. When I try to play the HLS streams, the player I was trying seems to have problems while loading the first videos. After some time, it seems like it starts doing fine.

Here is some information:

1. The parameters I am using for ffmpeg (listed below). The source is an mjpeg camera.
2. The first request of the player to get the playlist works just fine and this is how the returned playlist looks:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-MAP:URI="init-room.mp4"
#EXTINF:9.820000,
room1.m4s
#EXTINF:9.903000,
room2.m4s
#EXTINF:10.010000,
room3.m4s
```

3. The player plays the first 10 seconds just fine (I am guessing this is the init-id.mp4), but then most of the times it has problems continuing the stream for some time and then it continues.
What's weird is that you can see the requests for the video being made and downloaded, but the players have problems playing them.

4. The player I was trying is [hls-js](https://github.com/video-dev/hls.js/). If you just put any hls stream from ffmpeg-streamer from a camera on their [demo](https://hls-js.netlify.com/demo/) you should be able to recreate.

Here are some screenshots that hopefully can show what I mean:

Here you can see how the player has some video buffered, but refuses to play it, and it keeps making requests to get the playlist
![image](https://user-images.githubusercontent.com/24518083/65655424-c824c780-dfe1-11e9-91af-bc63068f2b62.png)

I did noticed something:
The player throws a media error that says:
```details: "bufferSeekOverHole", fatal: false, reason: "fragment loaded with buffer holes, seeking from 75.987958 to 77.932291", frag: t}```

I did try this in other players, one of them VHS (videojs-http-streaming) did not work at all, the one that comes with your project, and it seems to experience the same problem (but has a bit more luck recoverying) and VLC which is the only one that can play the stream without problems.

Do you think I may have some problems with the way I am running ffmpeg? I have not been able to figure out what the problem is.

```
 {
      "id": "room1",
      "name": "room1",
      "logLevel": "quiet",
      "params": [
          "-hwaccel",
          "auto",
          "-analyzeduration",
          "10000000",
          "-probesize",
          "1048576",
          "-re",
          "-use_wallclock_as_timestamps",
          "1",
          "-f",
          "mjpeg",
          "-i",
          "http://192.168.0.15/axis-cgi/mjpg/video.cgi?camera=1&resolution=352x240&1569462930455",
          "-an",
          "-c:v",
          "libx264",
          "-tune",
          "zerolatency",
          "-r",
          "15",
          "-vf",
          "scale=trunc(iw*0.9/2)*2:-2",
          "-min_frag_duration",
          "10000000",
          "-frag_duration",
          "10000000",
          "-crf",
          "15",
          "-preset",
          "veryfast",
          "-profile:v",
          "baseline",
          "-level:v",
          "3.1",
          "-pix_fmt",
          "yuv420p",
          "-f",
          "mp4",
          "-movflags",
          "+dash+negative_cts_offsets",
          "pipe:1",
          "-c",
          "mjpeg",
          "-q",
          "10",
          "-r",
          "7",
          "-vf",
          "scale=trunc(iw*0.75/2)*2:-2",
          "-f",
          "image2pipe",
          "pipe:4"
      ],
      "hlsBase": "room1",
      "hlsListSize": 10
  }
```

**Comment by kevinGodell** [comment]
Sorry for the late response. I never seem to get notifications from github. 

At first glance, it seems that you are doing 10 second duration chunks. Without knowing more details, I would think that maybe the file sizes are too big to be delivered in any fast way. 

That error about the "buffer seek over hole" seems that a chunk did not get delivered in time. And also, my code is meant for delivering "live" video and should not try to seek into the past since that video chunk will probably no longer exist in memory.

Is there any setting for your video player that you can tell it to treat video source as a live feed?
